export const CREAM_COLORS = {
  LIGHT_CREAM_FUR: '#FFE6BE',
  ORANGE_FUR: '#f79825',
  EYES_AND_NOSE: '#8D5929',
  DRESS_AND_SHOES: '#FF5A00',
  SHOES_YELLOW_PART_AND_BUTTONS: '#FEE100',
  BLUE_BOW: '#7FD3F8',
} as const;
