services:
  agent:
    platform: linux/amd64
    command: ['bun', 'start']
    image: cream-agent:amd64
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: always

  server:
    platform: linux/amd64
    command: ['bun', 'start']
    image: cream-server:amd64
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - '8080:8080'
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
